name: CI with Coverage

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov coveralls pyyaml
          python3 -m pip install -e .

      # Step 4: Run tests and collect coverage
      - name: Run Tests
        run: |
          pytest Regressions/test_automatic_regression.py -v --disable-warnings \
            --cov=RCAIDE \
            --cov-config=.coveragerc

      # Step 5: Upload coverage to Coveralls (only for Python 3.11 on Ubuntu)
      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}
        run: |
          coveralls
