name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  matrix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov
          python3 -m pip install -e .
      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest Regressions/test_automatic_regression.py -v --disable-warnings --cov=RCAIDE --cov-config=.coveragerc --cov-report=lcov:coverage.lcov
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage.lcov
          parallel: true
          path-to-lcov: coverage.lcov
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          flag-name: ${{ matrix.os }}-python-${{ matrix.python-version }}

  finish:
    needs: matrix-test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Coveralls of Parallel Finish
        run: |
          curl -k "https://coveralls.io/webhook?repo_token=${{ secrets.COVERALLS_REPO_TOKEN }}&repo_name=${{ github.repository }}" \
            -d "payload[build_num]=${{ github.run_id }}&payload[status]=done"