name: CI with Coveralls Parallel Build

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  matrix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        run: [run1, run2]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov coveralls
          python -m pip install -e .

      - name: Run Tests with Coverage for ${{ matrix.run }}
        env:
          COVERALLS_PARALLEL: true
        run: |
          coverage run -m pytest Regressions/test_${{ matrix.run }}.py -v --disable-warnings --cov=RCAIDE --cov-config=.coveragerc --cov-report=lcov:coverage.lcov

      - name: Send Coverage to Coveralls for ${{ matrix.run }}
        uses: coverallsapp/github-action@v1
        with:
          parallel: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: "os-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ matrix.run }}"

  finish:
    needs: matrix-test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Coveralls to Close Parallel Build
        uses: coverallsapp/github-action@v1
        with:
          parallel-finished: true
          carryforward: |
            os-ubuntu-latest-python-3.8-run1,
            os-ubuntu-latest-python-3.8-run2,
            os-ubuntu-latest-python-3.9-run1,
            os-ubuntu-latest-python-3.9-run2,
            os-ubuntu-latest-python-3.10-run1,
            os-ubuntu-latest-python-3.10-run2,
            os-ubuntu-latest-python-3.11-run1,
            os-ubuntu-latest-python-3.11-run2,
            os-ubuntu-latest-python-3.12-run1,
            os-ubuntu-latest-python-3.12-run2,
            os-windows-latest-python-3.8-run1,
            os-windows-latest-python-3.8-run2,
            os-windows-latest-python-3.9-run1,
            os-windows-latest-python-3.9-run2,
            os-windows-latest-python-3.10-run1,
            os-windows-latest-python-3.10-run2,
            os-windows-latest-python-3.11-run1,
            os-windows-latest-python-3.11-run2,
            os-windows-latest-python-3.12-run1,
            os-windows-latest-python-3.12-run2,
            os-macos-latest-python-3.8-run1,
            os-macos-latest-python-3.8-run2,
            os-macos-latest-python-3.9-run1,
            os-macos-latest-python-3.9-run2,
            os-macos-latest-python-3.10-run1,
            os-macos-latest-python-3.10-run2,
            os-macos-latest-python-3.11-run1,
            os-macos-latest-python-3.11-run2,
            os-macos-latest-python-3.12-run1,
            os-macos-latest-python-3.12-run2
