name: CI
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  matrix-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-cov
          python3 -m pip install -e .
          - name: Upload Coverage to Coveralls
          uses: coverallsapp/github-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            file: coverage.lcov
            flag-name: ${{ runner.os }}-${{ matrix.python-version }}
            parallel: true
            git-branch: ${{ github.head_ref || github.ref_name }}
  
  finish:
      needs: matrix-test
      if: always()
      runs-on: ubuntu-latest
      steps:
        - name: Wait
          run: sleep 30
          
        - name: Finalize Coveralls
          uses: coverallsapp/github-action@v2
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            parallel-finished: true
            git-branch: ${{ github.head_ref || github.ref_name }}