name: Docs

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessary for sphinx-multiversion to access all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx pydata-sphinx-theme sphinx-multiversion nbsphinx sphinx-copybutton myst-nb nbconvert nbformat jupyter

      - name: Execute Notebooks
        run: |
          for notebook in Tutorials/*/*.ipynb; do
            echo "Running $notebook"
            if [ -f "$notebook" ]; then
              jupyter nbconvert --to notebook --execute "$notebook" --output "$notebook" --ExecutePreprocessor.timeout=600
            else
              echo "Notebook $notebook not found."
            fi
          done

      - name: Clean Old Docs
        run: |
          rm -rf docs/source/_autosummary
          rm -rf docs/source/tutorials/Optimization docs/source/tutorials/Missions docs/source/tutorials/Performance

      - name: Copy tutorials to Docs
        run: |
          cp -r Tutorials/* docs/source/tutorials/

      - name: Build Multiversion Docs
        run: |
          sphinx-multiversion docs/source docs/build/html

      - name: Add Custom Domain
        run: |
          echo "www.docs.rcaide.leadsresearchgroup.com" > docs/build/html/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          # Optionally, set a custom branch for GitHub Pages
          # publish_branch: gh-pages
