name: docs

on:
    push:
      branches:
        - develop  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install sphinx pydata-sphinx-theme

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,optional]
        
      - name: Generate API Documentation
        run: |
          sphinx-apidoc -f -o source/ RCAIDE
      - name: Build HTML
        run: |
          cd docs
          make html

      - name: Add Custom Domain
        run: echo "www.docs.rcaide.leadsresearchgroup.com" > docs/build/html/CNAME
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html


          
          