name: Docs

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install sphinx pydata-sphinx-theme

      - name: Install Dependencies
        run: |
           python3 -m pip install --upgrade pip
           python3 -m pip install -e .
           python3 -m pip install sphinx sphinx_rtd_theme
           python3 -m pip install sphinx
           python3 -m pip install sphinx-rtd-theme
           python3 -m pip install sphinx-autobuild
           python3 -m pip install sphinx-autoapi
           python3 -m pip install nbsphinx
           python3 -m pip install sphinx-copybutton
           python3 -m pip install myst-nb
           python3 -m pip install pandoc


      - name: Generate API Documentation
        run: |
          sphinx-apidoc -f -o source/ RCAIDE
      - name: Build HTML
        run: |
          cd docs
          make html

      - name: Add Custom Domain
        if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
        run: echo "www.docs.rcaide.leadsresearchgroup.com" > docs/build/html/CNAME
        
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html


          
          